export const SET_CONTESTANT_DATA = 'SET_CONTESTANT_DATA';
export const SET_ELECTION_DATA = 'SET_ELECTION_DATA';
export const SET_ELECTION_RESULT = 'SET_ELECTION_RESULT';
export const SET_ELECTION_RESULT_DATA = 'SET_ELECTION_RESULT_DATA';
export const RESET_STATE = 'RESET_STATE';